safe:           true
lsi:            false
timezone:       America/Los_Angeles
markdown:       kramdown
highlighter:    rouge
gems:           [jekyll-paginate, jekyll-redirect-from]
whitelist:      [jekyll-redirect-from]

paginate:       10
paginate_path:  news/page:num

name:           Seattle GNU Linux Conference
short_name:     SeaGL
description:    Seattle GNU Linux Conference
url:            http://seagl.org

permalink:      /:categories/:year/:month/:day/:title.html

custom:
    year:                   2019
    dates:                  November 15th and 16th
    location:               Seattle Central College
    license:
        content:            <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a>

        site_code:          <a href="https://github.com/SeaGL/seagl.github.io/blob/master/LICENSE">GPL v3.0</a>
    url:
        irc:
            network:        https://freenode.net/kb/answer/chat
            channel:        https://webchat.freenode.net?randomnick=1&channels=%23seagl
        mailing_list:
            seagl_announce: https://groups.google.com/forum/#!forum/seagl_announce
            seagl_organize: https://groups.google.com/forum/#!forum/seagl_organize
        location:           https://seattlecentral.edu
        prospectus:         /sponsors/SeaGL_Exhibitor_Sponsor_Prospectus_2019.pdf
    a:
        irc:
            network:        <a href="https://freenode.net/kb/answer/chat">Freenode</a>
            channel:        <a href="https://webchat.freenode.net?randomnick=1&channels=%23seagl">#seagl</a>
        email:
            award:          <a href="mailto:&#097;&#119;&#097;&#114;&#100;&#064;&#115;&#101;&#097;&#103;&#108;&#046;&#111;&#114;&#103;">&#097;&#119;&#097;&#114;&#100;&#064;&#115;&#101;&#097;&#103;&#108;&#046;&#111;&#114;&#103;</a>
            participate:    <a href="mailto:%70%61%72%74%69%63%69%70%61%74%65%40%73%65%61%67%6c%2e%6f%72%67">&#x0070;&#x0061;&#x0072;&#x0074;&#x0069;&#x0063;&#x0069;&#x0070;&#x0061;&#x0074;&#x0065;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            press:          <a href="mailto:%70%72%65%73%73%40%73%65%61%67%6c%2e%6f%72%67">&#x0070;&#x0072;&#x0065;&#x0073;&#x0073;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            sponsor:        <a href="mailto:%73%70%6f%6e%73%6f%72%40%73%65%61%67%6c%2e%6f%72%67">&#x0073;&#x0070;&#x006f;&#x006e;&#x0073;&#x006f;&#x0072;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            staff:          <a href="mailto:%73%74%61%66%66%40%73%65%61%67%6c%2e%6f%72%67">&#x0073;&#x0074;&#x0061;&#x0066;&#x0066;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            coc:            <a href="mailto:%63%6f%63%40%73%65%61%67%6c%2e%6f%72%67">&#x0043;&#x004f;&#x0043;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
        social:
            twitter:        <a href="https://twitter.com/seagl">Twitter</a>
            facebook:       <a href="https://www.facebook.com/SeattleGnuLinuxConference">Facebook</a>
            youtube:        <a href="https://www.youtube.com/user/SeaglOrg">YouTube</a>
        mailing_list:
            seagl_announce: <a href="https://groups.google.com/forum/#!forum/seagl_announce">announcement mailing list</a>
            seagl_organize: <a href="https://groups.google.com/forum/#!forum/seagl_organize">seagl_organize</a>
        location:           <a href="https://seattlecentral.edu">Seattle Central College</a>
        donate:             <a href="https://my.fsf.org/civicrm/contribute/transact?reset=1&id=58">Donate to SeaGL</a>
    maps:
      google:
        apikey:             AIzaSyAwVEJ8kLu3tWyuBxZX9_hfMnNLJk7obk8
sass:
    sass_dir: _sass
    style: compressed
