safe:           true
lsi:            false
future:         false # Workaround for SeaGL/seagl.github.io#170
timezone:       America/Los_Angeles
markdown:       kramdown
highlighter:    rouge

# Allowed plugins: https://pages.github.com/versions/
plugins: &plugins
    - jekyll-paginate
    - jekyll-redirect-from
whitelist: *plugins

paginate:       10
paginate_path:  news/page:num

name:           Seattle GNU/Linux Conference
short_name:     SeaGL
description:    Seattle GNU/Linux Conference
origin:         https://seagl.org

permalink:      /:categories/:year/:month/:day/:title.html

exclude:
    - backstop
    - backstop.json
    - Dockerfile

    # Pending jekyll/jekyll#7188
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/

custom:
    year:                   2021
    dates:                  November 5th & 6th
    location:               Virtual
    license:
        content:            <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a>

        site_code:          <a href="https://github.com/SeaGL/seagl.github.io/blob/master/LICENSE">GPL v3.0</a>
    url:
        irc:
            network:        https://libera.chat/
            webchat:        https://web.libera.chat/#SeaGL
        mailing_list:
            seagl_announce: https://groups.google.com/forum/#!forum/seagl_announce
            seagl_organize: https://groups.google.com/forum/#!forum/seagl_organize
        location:           https://seattlecentral.edu
        prospectus:         /sponsors/SeaGL_Exhibitor_Sponsor_Prospectus_2021.pdf
        register:           https://osem.seagl.org/conferences/seagl2021/register/new
        cfp:                https://osem.seagl.org/conferences/seagl2021
        schedule:           https://osem.seagl.org/conferences/seagl2021/schedule/events
    a:
        irc:
            network:        <a href="https://libera.chat/">Libera.Chat</a>
            channel:        <a href="https://web.libera.chat/#SeaGL">#SeaGL</a>
        matrix:
            network:        <a href="https://matrix.org/">Matrix</a>
            room:           <a href="https://matrix.to/#/#SeaGL:seattlematrix.org">#SeaGL:seattlematrix.org</a>
        email:
            award:          <a href="mailto:&#097;&#119;&#097;&#114;&#100;&#064;&#115;&#101;&#097;&#103;&#108;&#046;&#111;&#114;&#103;">&#097;&#119;&#097;&#114;&#100;&#064;&#115;&#101;&#097;&#103;&#108;&#046;&#111;&#114;&#103;</a>
            participate:    <a href="mailto:%70%61%72%74%69%63%69%70%61%74%65%40%73%65%61%67%6c%2e%6f%72%67">&#x0070;&#x0061;&#x0072;&#x0074;&#x0069;&#x0063;&#x0069;&#x0070;&#x0061;&#x0074;&#x0065;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            press:          <a href="mailto:%70%72%65%73%73%40%73%65%61%67%6c%2e%6f%72%67">&#x0070;&#x0072;&#x0065;&#x0073;&#x0073;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            sponsor:        <a href="mailto:%73%70%6f%6e%73%6f%72%40%73%65%61%67%6c%2e%6f%72%67">&#x0073;&#x0070;&#x006f;&#x006e;&#x0073;&#x006f;&#x0072;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            staff:          <a href="mailto:%73%74%61%66%66%40%73%65%61%67%6c%2e%6f%72%67">&#x0073;&#x0074;&#x0061;&#x0066;&#x0066;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            coc:            <a href="mailto:%63%6f%63%40%73%65%61%67%6c%2e%6f%72%67">&#x0043;&#x004f;&#x0043;&#x0040;&#x0073;&#x0065;&#x0061;&#x0067;&#x006c;&#x002e;&#x006f;&#x0072;&#x0067;</a>
            cfp-help:       <a href="mailto:%63%66%70%2D%68%65%6C%70%40%73%65%61%67%6C%2E%6F%72%67">&#x63;&#x66;&#x70;&#x2D;&#x68;&#x65;&#x6C;&#x70;&#x40;&#x73;&#x65;&#x61;&#x67;&#x6C;&#x2E;&#x6F;&#x72;&#x67;</a>
        social:
            github:         <a href="https://github.com/SeaGL/">GitHub</a>
            mastodon:       <a href="https://mastodon.social/@SeaGL">Mastodon</a>
            pixelfed:       <a href="https://pixelfed.social/SeaGL">Pixelfed</a>
            twitter:        <a href="https://twitter.com/seagl">Twitter</a>
            facebook:       <a href="https://www.facebook.com/SeattleGnuLinuxConference">Facebook</a>
            youtube:        <a href="https://www.youtube.com/user/SeaglOrg">YouTube</a>
        mailing_list:
            seagl_announce: <a href="https://groups.google.com/forum/#!forum/seagl_announce">announcement mailing list</a>
            seagl_organize: <a href="https://groups.google.com/forum/#!forum/seagl_organize">seagl_organize</a>
        location:           <a href="https://seattlecentral.edu">Seattle Central College</a>
        donate:             <a href="https://my.fsf.org/civicrm/contribute/transact?reset=1&id=58">Donate to SeaGL</a>
    maps:
      google:
        apikey:             AIzaSyAwVEJ8kLu3tWyuBxZX9_hfMnNLJk7obk8
sass:
    sass_dir: _sass
    style: compressed
